In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm

In [2]:
# df for occupational data
# Table 1.1 Employment by major occupational group, 2021 and projected 2031 (Numbers in thousands)
df_occ = pd.read_excel('occupation.xlsx',sheet_name='Table 1.1',header=1,nrows=23)

In [3]:
df_occ = df_occ.rename(columns={'2021 National Employment Matrix title':'Occupation'})
df_occ.at[8,'Occupation'] = 'Education, training, and library occupations'

In [4]:
# df for demographic data
# Year: 2021
# Numbers in Thousands
df_dem = pd.read_excel('cpsaat11.xlsx',sheet_name='cpsaat11',header=3,nrows=599)

In [5]:
df_dem.at[0, 'Occupation'] = 'Total, all occupations'
#df_dem

In [6]:
'''NOTES: 
In order to merge the data from occupation.xlsx and cpsaat11.xlsx I had to rename
Educational instruction and library occupations in occupation.xlsx to 
Education, training, and library occupations in order to match the value in cpsaat11.xlsx

In order to merge the data from occupation.xlsx and cpsaat11.xlsx I had to rename
2021 National Employment Matrix title in occupation.xlsx to Occupation in order 
to match the value in cpsaat11.xlsx
''' 
df = pd.merge(df_occ, df_dem, on = 'Occupation')

In [7]:
df = df.rename(columns={"Employment, 2021": "Emp21", 
                   "Employment, 2031" : "Emp31",
                   "Employment change, 2021-31": "EmpChange21_31",
                   "Percent employment change, 2021-31": "PercentChange21_31",
                   "Median annual wage, 2021(1)": "MedianWage2021",
                   "Total Employed": "TotEmp",
                   "Percent of total employed Women": "PercentWomen",
                   "Percent of total employed White": "PercentWhite",
                   "Percent of total employed Black or\nAfrican\nAmerican": "PercentBlack",
                   "Percent of total employed Asian": "PercentAsian",
                   "Percent of total employed Hispanic\nor Latino": "PercenLatino"})
df

,Occupation,2021 National Employment Matrix code,Emp21,Emp31,EmpChange21_31,PercentChange21_31,MedianWage2021,TotEmp,PercentWomen,PercentWhite,PercentBlack,PercentAsian,PercenLatino
0,"Total, all occupations",00-0000,158134.7,166452.1,8317.4,5.3,45760,152581.0,47,77.5,12.3,6.6,18
1,Management occupations,11-0000,11685.3,12569.2,883.9,7.6,102450,18986.0,40.9,82.2,8.6,6.5,11.1
2,Business and financial operations occupations,13-0000,9987.4,10702.5,715.1,7.2,76570,8878.0,54.8,78,10.5,8.6,10.3
3,Computer and mathematical occupations,15-0000,4951.5,5716.3,764.8,15.4,97540,5688.0,26.2,65.4,8.5,23.3,8.3
4,Architecture and engineering occupations,17-0000,2562.5,2653.7,91.3,3.6,79840,3235.0,17.4,77,5.8,14.6,9.9
5,"Life, physical, and social science occupations",19-0000,1436.0,1534.7,98.7,6.9,72740,1640.0,47.4,74.6,7.4,15.2,8.3
6,Community and social service occupations,21-0000,2843.2,3137.8,294.6,10.4,48410,2777.0,67.5,72.9,19.7,3.8,12.5
7,Legal occupations,23-0000,1368.0,1499.0,131.0,9.6,82430,1805.0,53.5,84,8.1,4.8,10.4
8,"Education, training, and library occupations",25-0000,9151.2,9809.3,658.2,7.2,57220,8946.0,73.7,81.5,9.9,5.6,10.8
9,"Arts, design, entertainment, sports, and media...",27-0000,2789.1,2973.7,184.6,6.6,51190,3151.0,50,82.9,8.2,5.7,11.1
10,Healthcare practitioners and technical occupat...,29-0000,9228.2,10023.5,795.3,8.6,75040,9639.0,74.3,75.6,12,9.5,9.4
11,Healthcare support occupations,31-0000,7026.0,8279.7,1253.8,17.8,29880,4887.0,85.1,64.5,24.5,6.8,20.9
12,Protective service occupations,33-0000,3482.2,3554.8,72.6,2.1,46590,2987.0,23.8,72.5,20.3,2.7,14.9
13,Food preparation and serving related occupations,35-0000,11761.8,13081.6,1319.9,11.2,28400,7370.0,54.6,74.6,13.4,6.3,27.8
14,Building and grounds cleaning and maintenance ...,37-0000,5415.0,5705.8,290.8,5.4,30240,5482.0,41.7,78,14.2,3.4,38.3
15,Personal care and service occupations,39-0000,3868.4,4413.2,544.8,14.1,29450,3676.0,78.7,73,12.5,10.1,18
16,Sales and related occupations,41-0000,14719.9,14555.4,-164.5,-1.1,30600,14369.0,49.8,79.7,11.2,5.4,16.7
17,Office and administrative support occupations,43-0000,19587.0,18706.2,-880.8,-4.5,38050,15797.0,72.2,76.2,15,4.8,17.7
18,"Farming, fishing, and forestry occupations",45-0000,1069.6,1078.0,8.4,0.8,29860,1061.0,24.2,88.4,4.4,2.3,43.9
19,Construction and extraction occupations,47-0000,7026.0,7278.9,252.9,3.6,48210,8057.0,3.9,87.2,7.1,1.7,38.9
20,"Installation, maintenance, and repair occupations",49-0000,6038.7,6342.6,304.0,5.0,47940,4840.0,4.3,84.5,8.3,3.3,22
21,Production occupations,51-0000,8787.1,8623.5,-163.6,-1.9,37710,7950.0,28.3,77.6,13.3,5.5,24
22,Transportation and material moving occupations,53-0000,13350.7,14212.6,861.8,6.5,36860,11359.0,21.6,71.4,20.1,4.2,23.6

In [8]:
df.to_excel("occupation_demographics.xlsx")

## Occupations Least Total Job Growth

In [10]:
df.sort_values("EmpChange21_31").head(5)

,Occupation,2021 National Employment Matrix code,Emp21,Emp31,EmpChange21_31,PercentChange21_31,MedianWage2021,TotEmp,PercentWomen,PercentWhite,PercentBlack,PercentAsian,PercenLatino
17,Office and administrative support occupations,43-0000,19587.0,18706.2,-880.8,-4.5,38050,15797.0,72.2,76.2,15,4.8,17.7
16,Sales and related occupations,41-0000,14719.9,14555.4,-164.5,-1.1,30600,14369.0,49.8,79.7,11.2,5.4,16.7
21,Production occupations,51-0000,8787.1,8623.5,-163.6,-1.9,37710,7950.0,28.3,77.6,13.3,5.5,24
18,"Farming, fishing, and forestry occupations",45-0000,1069.6,1078.0,8.4,0.8,29860,1061.0,24.2,88.4,4.4,2.3,43.9
12,Protective service occupations,33-0000,3482.2,3554.8,72.6,2.1,46590,2987.0,23.8,72.5,20.3,2.7,14.9

## Occupations Most Total Job Growth

In [11]:
df.drop(index=0).sort_values("EmpChange21_31", ascending=False).head(5)

,Occupation,2021 National Employment Matrix code,Emp21,Emp31,EmpChange21_31,PercentChange21_31,MedianWage2021,TotEmp,PercentWomen,PercentWhite,PercentBlack,PercentAsian,PercenLatino
13,Food preparation and serving related occupations,35-0000,11761.8,13081.6,1319.9,11.2,28400,7370.0,54.6,74.6,13.4,6.3,27.8
11,Healthcare support occupations,31-0000,7026.0,8279.7,1253.8,17.8,29880,4887.0,85.1,64.5,24.5,6.8,20.9
1,Management occupations,11-0000,11685.3,12569.2,883.9,7.6,102450,18986.0,40.9,82.2,8.6,6.5,11.1
22,Transportation and material moving occupations,53-0000,13350.7,14212.6,861.8,6.5,36860,11359.0,21.6,71.4,20.1,4.2,23.6
10,Healthcare practitioners and technical occupat...,29-0000,9228.2,10023.5,795.3,8.6,75040,9639.0,74.3,75.6,12,9.5,9.4

## Occupations Least Percent Job Growth

In [12]:
df.sort_values("PercentChange21_31").head(5)

,Occupation,2021 National Employment Matrix code,Emp21,Emp31,EmpChange21_31,PercentChange21_31,MedianWage2021,TotEmp,PercentWomen,PercentWhite,PercentBlack,PercentAsian,PercenLatino
17,Office and administrative support occupations,43-0000,19587.0,18706.2,-880.8,-4.5,38050,15797.0,72.2,76.2,15,4.8,17.7
21,Production occupations,51-0000,8787.1,8623.5,-163.6,-1.9,37710,7950.0,28.3,77.6,13.3,5.5,24
16,Sales and related occupations,41-0000,14719.9,14555.4,-164.5,-1.1,30600,14369.0,49.8,79.7,11.2,5.4,16.7
18,"Farming, fishing, and forestry occupations",45-0000,1069.6,1078.0,8.4,0.8,29860,1061.0,24.2,88.4,4.4,2.3,43.9
12,Protective service occupations,33-0000,3482.2,3554.8,72.6,2.1,46590,2987.0,23.8,72.5,20.3,2.7,14.9

## Occupations Most Percent Job Growth

In [13]:
df.drop(index=0).sort_values("PercentChange21_31", ascending=False).head(5)

,Occupation,2021 National Employment Matrix code,Emp21,Emp31,EmpChange21_31,PercentChange21_31,MedianWage2021,TotEmp,PercentWomen,PercentWhite,PercentBlack,PercentAsian,PercenLatino
11,Healthcare support occupations,31-0000,7026.0,8279.7,1253.8,17.8,29880,4887.0,85.1,64.5,24.5,6.8,20.9
3,Computer and mathematical occupations,15-0000,4951.5,5716.3,764.8,15.4,97540,5688.0,26.2,65.4,8.5,23.3,8.3
15,Personal care and service occupations,39-0000,3868.4,4413.2,544.8,14.1,29450,3676.0,78.7,73,12.5,10.1,18
13,Food preparation and serving related occupations,35-0000,11761.8,13081.6,1319.9,11.2,28400,7370.0,54.6,74.6,13.4,6.3,27.8
6,Community and social service occupations,21-0000,2843.2,3137.8,294.6,10.4,48410,2777.0,67.5,72.9,19.7,3.8,12.5

## Occupations Smallest Percent White

In [14]:
df.sort_values("PercentWhite").head(5)

,Occupation,2021 National Employment Matrix code,Emp21,Emp31,EmpChange21_31,PercentChange21_31,MedianWage2021,TotEmp,PercentWomen,PercentWhite,PercentBlack,PercentAsian,PercenLatino
11,Healthcare support occupations,31-0000,7026.0,8279.7,1253.8,17.8,29880,4887.0,85.1,64.5,24.5,6.8,20.9
3,Computer and mathematical occupations,15-0000,4951.5,5716.3,764.8,15.4,97540,5688.0,26.2,65.4,8.5,23.3,8.3
22,Transportation and material moving occupations,53-0000,13350.7,14212.6,861.8,6.5,36860,11359.0,21.6,71.4,20.1,4.2,23.6
12,Protective service occupations,33-0000,3482.2,3554.8,72.6,2.1,46590,2987.0,23.8,72.5,20.3,2.7,14.9
6,Community and social service occupations,21-0000,2843.2,3137.8,294.6,10.4,48410,2777.0,67.5,72.9,19.7,3.8,12.5

## Occupations Smallest Percent White

In [15]:
df.drop(index=0).sort_values("PercentWhite", ascending=False).head(5)

,Occupation,2021 National Employment Matrix code,Emp21,Emp31,EmpChange21_31,PercentChange21_31,MedianWage2021,TotEmp,PercentWomen,PercentWhite,PercentBlack,PercentAsian,PercenLatino
18,"Farming, fishing, and forestry occupations",45-0000,1069.6,1078.0,8.4,0.8,29860,1061.0,24.2,88.4,4.4,2.3,43.9
19,Construction and extraction occupations,47-0000,7026.0,7278.9,252.9,3.6,48210,8057.0,3.9,87.2,7.1,1.7,38.9
20,"Installation, maintenance, and repair occupations",49-0000,6038.7,6342.6,304.0,5.0,47940,4840.0,4.3,84.5,8.3,3.3,22
7,Legal occupations,23-0000,1368.0,1499.0,131.0,9.6,82430,1805.0,53.5,84,8.1,4.8,10.4
9,"Arts, design, entertainment, sports, and media...",27-0000,2789.1,2973.7,184.6,6.6,51190,3151.0,50,82.9,8.2,5.7,11.1

In [23]:
df = df.astype({'PercentWomen': 'float64', 
                'PercentWhite':'float64',
                'PercentBlack':'float64',
                'PercentAsian':'float64',
                'PercenLatino':'float64',})
df.dtypes

Occupation                               object
2021 National Employment Matrix code     object
Emp21                                   float64
Emp31                                   float64
EmpChange21_31                          float64
PercentChange21_31                      float64
MedianWage2021                            int64
TotEmp                                  float64
PercentWomen                            float64
PercentWhite                            float64
PercentBlack                            float64
PercentAsian                            float64
PercenLatino                            float64
dtype: object

In [24]:
df['MedianWage2021'].corr(df['PercentWomen'])

-0.11408389525521567

In [25]:
regression = sm.ols(formula='MedianWage2021 ~ PercentWomen',data=df).fit(cov_type='HC1')
print(regression.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         MedianWage2021   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                 -0.034
Method:                 Least Squares   F-statistic:                    0.4265
Date:                Mon, 10 Oct 2022   Prob (F-statistic):              0.521
Time:                        19:09:12   Log-Likelihood:                -262.93
No. Observations:                  23   AIC:                             529.9
Df Residuals:                      21   BIC:                             532.1
Df Model:                           1
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     5.821e+04   9604.583      6.061      0.000    3.94e+04     7.7e+04
PercentWomen  -111.2955    170.410     -0.653      0.514    -445.293     222.702
==============================================================================
Omnibus:                        3.126   Durbin-Watson:                   0.884
Prob(Omnibus):                  0.210   Jarque-Bera (JB):                2.583
Skew:                           0.727   Prob(JB):                        0.275
Kurtosis:                       2.236   Cond. No.                         112.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)

In [26]:
regression = sm.ols(formula='MedianWage2021 ~ PercentBlack',data=df).fit(cov_type='HC1')
print(regression.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         MedianWage2021   R-squared:                       0.202
Model:                            OLS   Adj. R-squared:                  0.164
Method:                 Least Squares   F-statistic:                     7.454
Date:                Mon, 10 Oct 2022   Prob (F-statistic):             0.0125
Time:                        19:11:28   Log-Likelihood:                -260.49
No. Observations:                  23   AIC:                             525.0
Df Residuals:                      21   BIC:                             527.2
Df Model:                           1
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     7.714e+04    1.2e+04      6.416      0.000    5.36e+04    1.01e+05
PercentBlack -2002.3617    733.398     -2.730      0.006   -3439.794    -564.929
==============================================================================
Omnibus:                        0.553   Durbin-Watson:                   0.947
Prob(Omnibus):                  0.758   Jarque-Bera (JB):                0.624
Skew:                           0.302   Prob(JB):                        0.732
Kurtosis:                       2.465   Cond. No.                         33.6
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)

In [27]:
regression = sm.ols(formula='PercentChange21_31 ~ PercentWomen',data=df).fit(cov_type='HC1')
print(regression.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:     PercentChange21_31   R-squared:                       0.145
Model:                            OLS   Adj. R-squared:                  0.105
Method:                 Least Squares   F-statistic:                     3.087
Date:                Mon, 10 Oct 2022   Prob (F-statistic):             0.0935
Time:                        19:14:24   Log-Likelihood:                -69.098
No. Observations:                  23   AIC:                             142.2
Df Residuals:                      21   BIC:                             144.5
Df Model:                           1
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        2.4532      2.112      1.162      0.245      -1.686       6.592
PercentWomen     0.0874      0.050      1.757      0.079      -0.010       0.185
==============================================================================
Omnibus:                        4.132   Durbin-Watson:                   1.828
Prob(Omnibus):                  0.127   Jarque-Bera (JB):                2.303
Skew:                          -0.485   Prob(JB):                        0.316
Kurtosis:                       4.210   Cond. No.                         112.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)